<aside role="complementary">
  <h3><i class="fa fa-external-link fa-4x"></i>Links</h3>
    <dl>
      <dt>外部リンク <span>External link</span></dt>
      <dd><a href="http://symbol.ntt-west.co.jp/nw/baseball/pitcher.php" target="_blank"><span class="fa fa-users"></span>NTT西日本硬式野球部 選手紹介</a></dd>
      <dd><a href="https://symbol.ntt-west.co.jp/nw/sendmessage.php?tid=baseball" target="_blank"><span class="fa fa-comments"></span>応援メッセージを送る</a></dd>
      <dd><a href="http://www.ntt-west.co.jp/symbol/mobile_mail/index.html" target="_blank" class="banner"><span class="fa fa-envelope-o"></span>速報メールマガジン ご登録</a></dd>
      <dd><a href="http://www.ntt-west.co.jp/symbol/fan/index.html" target="_blank" class="banner"><span class="fa fa-user-plus"></span>ファンクラブ ご登録</a></dd>
    </dl>
</aside>
<footer role="contentinfo">
  <ul>
    <li><a href="/symbol/index.html" target="_blank">NTT西日本グループ　シンボルチーム</a></li>
    <li> <small>&copy; 2015　西日本電信電話株式会社</small></li>
  </ul>
</footer>
<!--<a href="/symbol/hp/baseball/games/2016/city/scoreboard.php" id="live"><img src="/symbol/hp/baseball/games/2016/city/img/common/live.png" width="278" height="138" alt="試合速報配信中！"></a>-->
<!--<a href="/symbol/hp/baseball/games/2016/city/hero.html" id="hero"><img src="/symbol/hp/baseball/games/2016/city/img/common/hero.png" width="160" height="160" alt="ヒーローインタビュー"></a>-->
<p id="pagetop"><a href="#top">▲</a></p>