<header role="banner" id="top">
  <h1><a href="/" target="_blank"><img src="/symbol/hp/baseball/games/2013/city/img/common/ci.gif" width="148" height="46" alt="NTT西日本"></a></h1>
  <ul id="topnavi">
    <li><a href="/" target="_blank">NTT西日本公式トップ</a></li>
    <li><a href="/share/aboutsite.html" target="_blank">このサイトについて</a></li>
    <li><a href="/share/privacy.html" target="_blank">プライバシーポリシー</a></li>
  </ul>
  <h2><a href="/symbol/hp/baseball/games/2016/city/index.html"><img src="img/common/logo.png" alt="第87回都市対抗野球大会"></a></h2>
</header>
<nav id="global" role="navigation">
  <h3><i class="fa fa-navicon fa-4x"></i>Menu</h3>
  <dl class="list-group">
  <dt>メインメニュー <span>Main Menu</span></dt>
    <dd><a href="/symbol/hp/baseball/games/2016/city/index.html"><span class="list-group-item fa fa-home"></span>トップページ<i>Top Page</i></a></dd>
    <dd><a href="/symbol/hp/baseball/games/2016/city/tournament.html"><span class="list-group-item fa fa-sitemap"></span>トーナメント表<i>Tournament Bracket</i></a></dd>
    <dd><a href="/symbol/hp/baseball/games/2016/city/results.html"><span class="list-group-item fa fa-list-ol"></span>試合結果<i>Results</i></a></dd>
    <dd><a href="/symbol/hp/baseball/games/2016/city/gallery.html"><span class="list-group-item fa fa-camera"></span>ギャラリー<i>Photo gallery</i></a></dd>
    <dd><a href="/symbol/hp/baseball/games/2016/city/aid.html"><span class="list-group-item fa fa-volume-up"></span>応援ガイド<i>Guidance of aid</i></a></dd>
    <dd><a href="/symbol/hp/baseball/games/2016/city/access.html"><span class="list-group-item fa fa-map-marker"></span>アクセスガイド<i>Guidance to a stadium</i> </a> </dd>
  <dt>トピックス <span>Topics</span></dt>
      <dd><a href="/symbol/hp/baseball/games/2016/city/hero.html"><span class="list-group-item fa fa-microphone"></span>ヒーローインタビュー<i>Hero Interview</i></a></dd>
      <dd><a href="/symbol/hp/baseball/games/2016/city/mascot.html"><span class="list-group-item fa fa-pencil-square-o"></span>マスコットの会場リポート<i>The mascot's game report</i></a></dd>
      <dd><a href="/symbol/hp/baseball/games/2016/city/history.html"><span class="list-group-item fa fa-trophy"></span>日本選手権とNTTグループの歴史<i>History</i></a></dd>
      <dd><a href="/symbol/hp/baseball/games/2016/city/past.html"><span class="list-group-item fa fa-book"></span>NTT西日本 過去の戦績<i>The past results</i></a></dd>
  </dl>
</nav>